---
- name: Configuring multiple users to worker
  hosts: worker
  user: ansible
  become: yes
  connection: ssh
  vars:
    users:
      - username: dev1
        password: $6$krmC2SZgZWEYTVNl$9KR6dfwP1Be7r60XfNVBm4.N/1A7FTXLxXT3FOzJCmPC4c1Mr0eIpoAkYEIY3rGVc6tWo.Srms/dE9MTDj1KQ1
        shell: /bin/bash
      - username: dev2
        password: $6$krmC2SZgZWEYTVNl$9KR6dfwP1Be7r60XfNVBm4.N/1A7FTXLxXT3FOzJCmPC4c1Mr0eIpoAkYEIY3rGVc6tWo.Srms/dE9MTDj1KQ1
        shell: /bin/bash

  tasks:
    - name: Configuring users on worker node
      user:
        name: "{{ item.username }}"
        password: "{{ item.password }}"
        shell: "{{ item.shell }}"
        state: present
      loop: "{{ users }}"
